name: Flat
on:
  workflow_dispatch: null
  push:
    paths:
      - .github/workflows/flat.yml
permissions:
  contents: write
  pages: read
  id-token: write
concurrency:
  group: flat
  cancel-in-progress: true
jobs:
  runs-on: ubuntu-latest
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
