name: Flat

on:
    workflow_dispatch: 

permissions:
    contents: write
    pages: read
    id-token: write

concurrency:
    group: "flat"
    cancel-in-progress: true

jobs:
    runs-on: ubuntu-latest